### ISSUE TITLE
Web archive versions of external links

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#10]
Are you able to generate a list of external links? @jmulliken can do the work to convert appropriate ones to archive versions, but if @lmullen  can provide the URLs, that will help.

**Comment by lmullen** [comment]
[apb-external-links.txt](https://github.com/lmullen/americas-public-bible/files/9536379/apb-external-links.txt)

@jmulliken Here is a list of unique external links.

Since this issue does not entail any changes to the repository itself, I am closing this issue.
