### ISSUE TITLE
Newspaper titles

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#17]
Edit/add data fields in ChronAm API for newspaper titles that use CMOS (title case; no "the"). Will attach stylesheet to this issue by 8/15.

**Comment by jmulliken** [comment]
From the stylesheet:

**Newspaper Titles**
Standalone (as in a list)
![image](https://user-images.githubusercontent.com/17858407/184403145-c75e32c0-3ec4-4b6c-aabb-53a12d87a765.png)

**Comment by lmullen** [comment]
This is corrected in the database. If there are any further corrections, I will need to know the specific newspapers to correct.
