### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by lmullen** [lmullen/americas-public-bible#18]
@jmulliken Can you please send me the Markdown for the terms of use page? I can add it, but I figure the press is the one that wants to draft that page.

**Comment by jmulliken** [comment]
We will be building, loading, and hosting the cover and TOU in a separate space. The cover page will include an Enter button that will link into the current landing page of the project. You won't need to worry at all about adding the cover and TOU to this repo.

**Comment by lmullen** [comment]
Okay, great. If it is not part of this repository I am going to close this issue.
