### ISSUE TITLE
Update cover image when it is finalized

### ISSUE THREAD

**Issue by lmullen** [lmullen/americas-public-bible#23]
Simply replacing `cover.png` should suffice.

**Comment by jmulliken** [comment]
You can grab any size from [https://sup.org/books/cite/?id=28910](https://sup.org/books/cite/?id=28910)

**Comment by lmullen** [comment]
Thanks. I didn't realize that was publicly available. I'm glad the press provides high-quality cover images like that; more presses should do the same.

This is finished.
