### ISSUE TITLE
Footer Edits

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#5]
It will most likely be the designer that tackles this  (and/or @jmulliken). Here are the specs, and we will move the relevant items in the current footer to the TOU:

 (@lmullen please comment with location in repo to add footer code.)

![image](https://user-images.githubusercontent.com/17858407/178025947-d3b65c58-0425-4b6e-b378-c67dfe22e91b.png)

![footer](https://user-images.githubusercontent.com/17858407/178025792-6a3ec021-ee62-43d2-ac4c-b1ab716193b7.png)
![logo_stanford](https://user-images.githubusercontent.com/17858407/178025796-0e79b7f2-dbd5-47e6-af66-2edcee57f37c.svg)

**Comment by jmulliken** [comment]
I've written up the HTML and CSS for the footer. @lmullen let me know where to add each. My best guess is website/layouts/_default/baseof.html for the HTML, but I'm not sure where the CSS should go. 

Also, we can move previous footer information that needs to be retained to the Terms of Use page. Is there anything in the footer you are obligated to keep upon publication per any other agreements?

For reference here is a sample screenshot:
![Screen Shot 2022-08-12 at 9 43 19 AM](https://user-images.githubusercontent.com/17858407/184405091-dadddc90-9f9e-4186-a692-bd86e8847fd4.png)

**Comment by lmullen** [comment]
@jmulliken You can either drop the HTML and CSS in this issue, if you like, and I will put them in, or you can send changes to `website/layouts/_default/baseof.html` and `website/assets/css/main.css` as a PR. Whichever is best.

**Comment by lmullen** [comment]
To your other question:

- We need to keep the "created at RRCHNM" and RRCHNM logo somewhere on the home page. It does not have to be on this footer, but at the bottom of the home page is fine. I will move it.
- All rights are not reserved. The "book" itself is to be released under a Creative Commons license, as on the current footer, and I retain copyright on the code which is licensed MIT, and the data is licensed CC0. It would be nice to put the CC license in the footer in place of the "all rights reserved" language and spell the rest out in the terms of use.
- I need to retain the acknowledgement to the GMU Office of Research Computing, but that is taken care of in the acknowledgements.

Does that help?

**Comment by lmullen** [comment]
@jmulliken Following up on this. Do you have the HTML and CSS you want me to use? If so, I can add them.

**Comment by jmulliken** [comment]
Here is a link to the CSS and HTML in one (can be separated and edited to fit existing CSS): [Footer](https://drive.google.com/file/d/1TXc5OqOdprf8MWH9O2HWQoQVVHpYgD7M/view?usp=sharing)

- Moving the RRCHNM to bottom of body sounds good to me.
- "All rights reserved" doesn't actually appear in our footer anymore. (I've changed that in the linked file.) Here's [an example](https://layeredlives.org/tou/index.html) of a typical Terms of Use page that includes CC info as laid out by our rights manager. Let me know if there are changes you'd like us to request for that page (e.g. MIT license info) This may already be a discussion you're having or have had with Friederike and I'm just not in the know; she typically gives the cover designer the terms-of-use copy when we do the cover which hasn't happened yet.
- Your last point is what makes me think you've already discussed all this with Friederike.

**Comment by lmullen** [comment]
@jmulliken Can you send me the `logo_stanford.svg` file, please?

**Comment by lmullen** [comment]
Ah, my mistake. I see that it must be the SVG up above.

**Comment by lmullen** [comment]
@jmulliken The code you sent does not work correctly. It does put the footer there, but it does not display the way that you intend. Perhaps there are some interactions between the existing site CSS and what is being added. I tried to resolve that, but it's not my area so I think it would be better if the press handled it. I will create a branch tomorrow with the code integrated so you can see the problem and propose a solution.

**Comment by lmullen** [comment]
@jmulliken As I mentioned, the footer code provided does not work correctly. I have integrated it into the site so that the press can make corrections. The changes are in the [footer branch](https://github.com/lmullen/americas-public-bible/pull/19). You can add your changes to that branch.

Could you designer please try to minimize the amount of CSS? The total amount of custom CSS for the whole site is 300 lines; the footer CSS provided adds about an additional 200 lines, which is disproportionate to the need.
