### ISSUE TITLE
RRCHNM Agreement

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#7]
Please confirm how long RRCHNM will host the data being served via API. Provide any terms of service or contracts that define the arrangement.

**Comment by lmullen** [comment]
Here is RRCHNM's [data API](https://github.com/chnm/apiary). The data API is a core component of RRCHNM's technical infrastructure. It serves our three biggest "big data" projects: America's Public Bible, American Religious Ecologies, and Death by Numbers. Other projects will be using it too. It is maintained by me, our lead developer, and our systems administrator. We plan on maintaining it indefinitely (and we have a 27+ year track record of maintaining projects). Should it be eliminated, Stanford University Press would have to take a place in line behind the NEH and the NSF to express its outrage. 😅

I am certainly sympathetic to the concern about external dependencies. If SUP wants to host a version of this API, you are welcome to create a version, but that would be a major lift. But I think that the stability of this API is as reasonable to rely on as any other dependency created in the academic world.

**Comment by lmullen** [comment]
Specifically in terms of terms of service or contracts, we don't have anything formal like that. But I am the Director of Computational History at RRCHNM and maintaining the data API falls under my core responsibilities. My colleague and one of the faculty directors who manages our sustainability efforts is also a stakeholder.

**Comment by jmulliken** [comment]
Sounds good. I'm keeping the issue open so we can return to it when it comes time to create the web archive. We may need to provide the crawler with some custom data to try and get it to capture the API functionality. Additionally, we'll want a dump of the DB to store in SDR alongside the publication build files.
