### ISSUE TITLE
Analytics (Optional)

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#8]
Remove Plausible in lieu of direct server analytics managed by SUP. (Totally optional as long as the plugin doesn't jeopardize longevity or preservation efforts. In other words, if the plugin breaks, will it prevent the site from loading? If the site is emulated in a virtual machine will the call to the plugin prevent the rest of the site content from loading?)

**Comment by lmullen** [comment]
This is not a plug in. It is simply a single call to Plausible's JavaScript. Were Plausible to go down, it would simply 404, and users would not notice. 

The analytics are implemented [here](https://github.com/lmullen/americas-public-bible/blob/main/website/layouts/partials/analytics.html).

I'll think about whether to remove it or not. Thanks for the option.
