### ISSUE TITLE
External v Local code/asset source

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#9]
Foundation (CSS/JS) delivered via CDN; fonts delivered by Google fonts; 
Please move into the project.

**Comment by jmulliken** [comment]
As a follow-up, we'll need to license the font for the web, so @lmullen if you can let me know which fonts specifically we need, I can get that process started and even download the fonts to add to the repo. Then you'll just need to link them into the stylesheet once it's pulled in as well.

**Comment by lmullen** [comment]
@jmulliken The only font is [IBM Plex Serif](https://github.com/IBM/plex) which is open source.

**Comment by lmullen** [comment]
I have done this for external JS and CSS. I am not going to do this for the Google Fonts. The likelihood of Google Fonts being the first thing to break is incredibly remote. If that were to happen, the site would gracefully degrade to a different font, and it would be easily fixed. The performance implications for changing the font are not worth this change.
